name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set Up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
          bb: latest

      - name: Prepare Babashka Deps
        run: bb prepare

      - name: Run Tests
        run: ./bin/ttt-test
